name: Sync to Repository B

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Source Files
        run: |
          mkdir /tmp/source

          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            ./ /tmp/source/

      - name: Clone Target Repo
        env:
          PAT: ${{ secrets.B_PAT }}
        run: |
          git clone \
            https://x-access-token:${PAT}@github.com/GhostC-SQ/hello.git \
            /tmp/target

      - name: Sync Files
        run: |
          rsync -av --delete \
            /tmp/source/ \
            /tmp/target/

      - name: Commit And Push
        env:
          PAT: ${{ secrets.B_PAT }}
        run: |
          cd /tmp/target

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          git diff --cached --quiet && exit 0

          git commit -m "sync from source repository"

          git push origin main
